== About Node.js Streams
Like unix pipes, Node streams are great for streaming chunks of data between
readers and writers to create arbitrary data processing pipelines.

Streams normally operate on strings and `Buffer` (or `Uint8Array`) objects.
In `object mode`, streams can also operate on arbitrary javascript values.

=== Buffering
Streams buffer incoming/outgoing data depending on the `highWaterMark` option.
For normal streams, the `highWaterMark` specifies a total number of bytes. For
object mode streams, the `highWaterMark` species a total number of objects.

When the size of the internal buffer reaches the `highWaterMark` threshold, the
stream will temporarily pause reading/writing data until that data is consumed.

A key goal of the stream API is to limit the buffering of data to acceptable
levels such that sources and destinations of differing speeds will not overwhelm
the available memory.

=== Encoding
Specifying an encoding causes the stream data to be returned as strings of the
specified encoding rather than as `Buffer` objects. By default, encoding is unspecified.
